-- DELETE EXISTING TABLES IF THEM EXIST
DROP TABLE IF EXISTS GROUP_PERMISSIONS CASCADE;
DROP TABLE IF EXISTS USER_PERMISSIONS CASCADE;
DROP TABLE IF EXISTS USER_GROUPS CASCADE;
DROP TABLE IF EXISTS PERMISSION CASCADE;
DROP TABLE IF EXISTS "GROUP" CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS CATS_ADOPTED CASCADE;
DROP TABLE IF EXISTS CAT_PHOTOS CASCADE;
DROP TABLE IF EXISTS CATS_FOR_ADOPTION CASCADE;
DROP TABLE IF EXISTS SHELTERS CASCADE;

--  CREATE TABLE SHELTERS
CREATE TABLE SHELTERS (
    SHELTER_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    STREET VARCHAR(50) NOT NULL,
    POSTAL_CODE VARCHAR(50) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    PHONE_NUMBER VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(50)
);

--  CREATE TABLE USERS
CREATE TABLE USERS (
    USER_ID SERIAL PRIMARY KEY,
    LOGIN VARCHAR(150) NOT NULL,
    PASSWORD VARCHAR(150) NOT NULL,
    FIRST_NAME VARCHAR(150),
    PHONE VARCHAR(150),
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    IS_STAFF BOOLEAN NOT NULL,
    LAST_NAME VARCHAR(150) NOT NULL,
    IS_SUPERUSER BOOLEAN,
    IS_ACTIVE BOOLEAN,
    LAST_LOGIN DATE,
    DATE_JOINED DATE
);

--  CREATE TABLE CATS FOR ADOPTION
CREATE TABLE CATS_FOR_ADOPTION (
    CAT_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    AGE INTEGER NOT NULL,
    BREED VARCHAR(30) NOT NULL,
    GENDER VARCHAR(10) NOT NULL,
    COLOR VARCHAR(20) NOT NULL,
    NOTES TEXT,
    SHELTER_ID INTEGER NOT NULL,
    CONSTRAINT FK_SHELTER_ID FOREIGN KEY (SHELTER_ID) REFERENCES SHELTERS(SHELTER_ID)
);

-- CREATE TABLE CAT PHOTOS
CREATE TABLE CAT_PHOTOS (
    PHOTO_CAT_ID SERIAL PRIMARY KEY,
    CAT_PHOTO_NAME VARCHAR(100) NOT NULL,
    CAT_ID INTEGER NOT NULL,
    CONSTRAINT FK_CAT_ID FOREIGN KEY (CAT_ID) REFERENCES CATS_FOR_ADOPTION(CAT_ID)
);

--  CREATE TABLE CATS ADOPTED
CREATE TABLE CATS_ADOPTED (
    ADOPTION_ID SERIAL PRIMARY KEY,
    ADOPTION_DATE DATE NOT NULL,
    CAT_ID INTEGER NOT NULL UNIQUE,
    USER_ID INTEGER NOT NULL,
    CONSTRAINT FK_CAT_ID FOREIGN KEY (CAT_ID) REFERENCES CATS_FOR_ADOPTION(CAT_ID),
    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- CREATE TABLE GROUP
CREATE TABLE "GROUP" (
    GROUP_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(150) NOT NULL
);

-- CREATE TABLE PERMISSION
CREATE TABLE PERMISSION (
    PERMISSION_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    CODE_NAME VARCHAR(100) NOT NULL
);

-- CREATE TABLE GROUP PERMISSIONS
CREATE TABLE GROUP_PERMISSIONS (
    GROUP_ID INTEGER NOT NULL,
    PERMISSION_ID INTEGER NOT NULL,
    PRIMARY KEY (GROUP_ID, PERMISSION_ID),
    CONSTRAINT FK_GROUP_ID FOREIGN KEY (GROUP_ID) REFERENCES "GROUP"(GROUP_ID),
    CONSTRAINT FK_PERMISSION_ID FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSION(PERMISSION_ID)
);

-- CREATE TABLE USER GROUPS
CREATE TABLE USER_GROUPS (
    USER_ID INTEGER NOT NULL,
    GROUP_ID INTEGER NOT NULL,
    PRIMARY KEY (USER_ID, GROUP_ID),
    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_GROUP_ID FOREIGN KEY (GROUP_ID) REFERENCES "GROUP"(GROUP_ID)
);

-- CREATE TABLE USER PERMISSIONS
CREATE TABLE USER_PERMISSIONS (
    USER_ID INTEGER NOT NULL,
    PERMISSION_ID INTEGER NOT NULL,
    PRIMARY KEY (USER_ID, PERMISSION_ID),
    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_PERMISSION_ID FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSION(PERMISSION_ID)
);

-- INSERTING SAMPLE DATA INTO THE SHELTERS TABLE
INSERT INTO SHELTERS (NAME, STREET, POSTAL_CODE, CITY, COUNTRY, PHONE_NUMBER, EMAIL)
VALUES  ('Warszawskie Schornisko', 'Ogrodnicza 26', '51-007', 'Wrocław',
        'Poland', '123-423-231', 'TOZ_schronisko@gmail.com'),
        ('Górskie Schronisko', 'Krakowska 15', '30-010', 'Kraków',
        'Poland', '456-678-234', NULL),
        ('Leśne Azyl', 'Leśna 8', '40-100', 'Katowice',
        'Poland', '789-890-345', 'lesneazyl@gmail.com'),
        ('Morskie Schronienie', 'Portowa 3', '71-001', 'Szczecin',
        'Poland', '321-432-567', 'morskieschronienie@gmail.com'),
        ('Tatrzański Azyl', 'Tatrzańska 21', '34-500', 'Zakopane',
        'Poland', '654-123-456', 'tatrzanskiazyl@gmail.com'),
        ('Podlasie Schronisko', 'Białostocka 7', '15-001', 'Białystok',
        'Poland', '987-654-321', NULL);

-- INSERTING SAMPLE DATA INTO THE USERS TABLE
INSERT INTO USERS (LOGIN, PASSWORD, FIRST_NAME, LAST_NAME, PHONE, EMAIL, IS_STAFF, IS_SUPERUSER, IS_ACTIVE, LAST_LOGIN,
                   DATE_JOINED)
VALUES
        -- SUPERUSERS
        ('super_admin', 'securePass123', 'Hubert', 'Kowalski',
         '123-456-789', 'super.admin@example.com', TRUE, TRUE, TRUE,
         '2024-12-01', '2024-01-01'),

        -- STAFF USERS
        ('staff_user1', 'pass1234', 'Adam', 'Nowak',
         NULL, 'staff1@example.com', TRUE, FALSE, TRUE,
         NULL, '2024-02-15'),
        ('staff_user2', 'secure123', 'Ewa', 'Wiśniewska',
         '987-654-321', 'staff2@example.com', TRUE, FALSE, TRUE,
         '2024-11-01', '2024-03-10'),
        ('staff_user3', 'mypass456', 'Michał', 'Lewandowski',
         NULL, 'staff3@example.com', TRUE, FALSE,
         TRUE, NULL, '2024-04-22'),

        -- STAFF SHELTERS
        ('staff_shelter1', 'pass1234', 'Kamil', 'Nowak',
         NULL, 'staff_shelter1@example.com', FALSE, FALSE, TRUE,
         NULL, '2024-06-15'),
        ('staff_shelter2', 'secure123', 'Mirek', 'Wiśniewski',
         '947-654-321', 'staff_shelter2@example.com', FALSE, FALSE, TRUE,
         '2024-12-01', '2024-03-23'),
        ('staff_shelter3', 'mypass456', 'Bogdan', 'Lewandowski',
         NULL, 'staff_shelter3@example.com', FALSE, FALSE,
         TRUE, NULL, '2024-04-21'),

        -- REGULAR USERS
        ('user01', 'userpass01', 'Anna', 'Kowal',
         '555-123-456', 'user01@example.com', FALSE, FALSE, TRUE,
         NULL, '2024-05-10'),
        ('user02', 'userpass02', NULL, 'Wiśniewski',
         '555-654-321', 'user02@example.com', FALSE, FALSE, TRUE,
         '2024-11-10', '2024-06-12'),
        ('user03', 'userpass03', 'Piotr', 'Kaczmarek',
         NULL, 'user03@example.com', FALSE, FALSE, TRUE,
         '2024-10-01', '2024-07-14'),
        ('user04', 'userpass04', 'Jan', 'Zieliński',
         '555-987-654', 'user04@example.com', FALSE, FALSE, TRUE,
         '2024-09-15', '2024-08-20'),
        ('user05', 'userpass05', 'Karolina', 'Woźniak',
         NULL, 'user05@example.com', FALSE, FALSE, TRUE,
         '2024-08-21', '2024-09-01'),
        ('user06', 'userpass06', 'Paulina', 'Kowalczyk',
         '555-222-333', 'user06@example.com', FALSE, FALSE, TRUE,
         NULL, '2024-10-11'),
        ('user07', 'userpass07', 'Rafał', 'Mazur',
         '555-333-444', 'user07@example.com', FALSE, FALSE, TRUE,
         '2024-07-01', '2024-11-01'),
        ('user08', 'userpass08', 'Jakub', 'Wojciechowski',
         '555-444-555', 'user08@example.com', FALSE, FALSE, TRUE,
         NULL, '2024-12-01'),
        ('user09', 'userpass09', 'Marcin', 'Kwiatkowski',
         NULL, 'user09@example.com', FALSE, FALSE, TRUE,
         '2024-06-01', '2024-01-15'),
        ('user10', 'userpass10', 'Agnieszka', 'Zając',
         '555-555-666', 'user10@example.com', FALSE, FALSE, TRUE,
         NULL, '2024-02-05'),
        ('user11', 'userpass11', 'Katarzyna', 'Król',
         '555-666-777', 'user11@example.com', FALSE, FALSE, TRUE,
         NULL, '2024-03-06'),
        ('user12', 'userpass12', 'Andrzej', 'Wieczorek',
         NULL, 'user12@example.com', FALSE, FALSE, TRUE,
         '2024-04-07', '2024-04-08'),
        ('user13', 'userpass13', 'Dawid', 'Jankowski',
         NULL, 'user13@example.com', FALSE, FALSE, TRUE,
         NULL, '2024-05-09'),
        ('user14', 'userpass14', 'Wojciech', 'Sikora',
         '555-777-888', 'user14@example.com', FALSE, FALSE, TRUE,
         '2024-12-11', '2024-06-10'),
        ('user15', 'userpass15', 'Kamil', 'Wróbel',
         '555-888-999', 'user15@example.com', FALSE, FALSE, TRUE,
         NULL, '2024-07-12'),
        ('user16', 'userpass16', 'Natalia', 'Nowakowska',
         NULL, 'user16@example.com', FALSE, FALSE, TRUE,
         NULL, '2024-08-13'),
        ('user17', 'userpass17', 'Magdalena', 'Grabowska',
         NULL, 'user17@example.com', FALSE, FALSE, TRUE,
         '2024-10-14', '2024-09-14'),
        ('user18', 'userpass18', 'Barbara', 'Stępień',
         NULL, 'user18@example.com', FALSE, FALSE, TRUE,
         NULL, '2024-11-15'),
        ('user19', 'userpass19', 'Ewelina', 'Pawlak',
         '555-999-111', 'user19@example.com', FALSE, FALSE, TRUE,
         NULL, '2024-12-16'),
        ('user20', 'userpass20', 'Łukasz', 'Michalak',
         NULL, 'user20@example.com', FALSE, FALSE, TRUE,
         '2024-01-17', '2024-02-18'),
        ('user21', 'userpass21', 'Tomasz', 'Sobczak',
         '555-111-222', 'user21@example.com', FALSE, FALSE, TRUE,
         NULL, '2024-03-19'),
        ('user22', 'userpass22', 'Patryk', 'Górski',
         '555-222-333', 'user22@example.com', FALSE, FALSE, TRUE,
         '2024-04-20', '2024-05-21'),
        ('user23', 'userpass23', 'Marta', 'Rogalska',
         NULL, 'user23@example.com', FALSE, FALSE, TRUE,
         NULL, '2024-06-22'),
        ('user24', 'userpass24', 'Justyna', 'Borkowska',
         NULL, 'user24@example.com', FALSE, FALSE, TRUE,
         NULL, '2024-07-23'),
        ('user25', 'userpass25', 'Grzegorz', 'Szulc',
         NULL, 'user25@example.com', FALSE, FALSE, TRUE,
         '2024-08-24', '2024-09-25'),
        ('user26', 'userpass26', 'Janina', 'Wójcik',
         NULL, 'user26@example.com', FALSE, FALSE, TRUE,
         NULL, '2024-10-26'),
        ('user27', 'userpass27', 'Irena', 'Malinowska',
         NULL, 'user27@example.com', FALSE, FALSE, TRUE,
         '2024-11-27', '2024-12-28'),
        ('user28', 'userpass28', 'Dominika', 'Pietrzak',
         NULL, 'user28@example.com', FALSE, FALSE, TRUE,
         NULL, '2024-01-29'),
        ('user29', 'userpass29', 'Izabela', 'Szymczak',
         NULL, 'user29@example.com', FALSE, FALSE, TRUE,
         '2024-02-28', '2024-03-01'),
        ('user30', 'userpass30', 'Krzysztof', 'Olszewski',
         NULL, 'user30@example.com', FALSE, FALSE, TRUE,
         '2024-03-02', '2024-04-03'),
        ('user31', 'userpass31', 'Beata', 'Majewska',
         NULL, 'user31@example.com', FALSE, FALSE, TRUE,
         NULL, '2024-05-04'),
        ('user32', 'userpass32', 'Sebastian', 'Sadowski',
         NULL, 'user32@example.com', FALSE, FALSE, TRUE,
         NULL, '2024-06-05'),
        ('user33', 'userpass33', 'Artur', 'Śliwiński',
         NULL, 'user33@example.com', FALSE, FALSE, TRUE,
         '2024-07-06', '2024-08-07'),
        ('user34', 'userpass34', 'Aleksander', 'Czarnecki',
         NULL, 'user34@example.com', FALSE, FALSE, TRUE,
         NULL, '2024-09-08'),
        ('user35', 'userpass35', 'Olga', 'Dąbrowska',
         NULL, 'user35@example.com', FALSE, FALSE, TRUE,
         '2024-10-09', '2024-11-10'),
        ('user36', 'userpass36', 'Tadeusz', 'Kołodziej',
         NULL, 'user36@example.com', FALSE, FALSE, TRUE,
         '2024-12-11', '2024-01-12');


-- INSERTING SAMPLE DATA INTO THE CATS FOR ADOPTION TABLE
INSERT INTO CATS_FOR_ADOPTION (NAME, AGE, BREED, GENDER, COLOR, NOTES, SHELTER_ID)
VALUES  ('Milo', 2, 'British Shorthair', 'Male', 'Gray',
         'Friendly and playful', 1),
        ('Luna', 3, 'Siamese', 'Female', 'Cream',
         'Loves attention', 1),
        ('Oliver', 1, 'Maine Coon', 'Male', 'Brown',
         'Curious and active', 1),
        ('Bella', 4, 'Persian', 'Female', 'White',
         'Calm and affectionate', 1),
        ('Leo', 2, 'Bengal', 'Male', 'Spotted',
         'Energetic and playful', 1),
        ('Chloe', 3, 'Ragdoll', 'Female', 'Blue',
         'Gentle and friendly', 1),
        ('Max', 5, 'Sphynx', 'Male', 'Pink',
         'Loves cuddling', 1),
        ('Simba', 1, 'Abyssinian', 'Male', 'Fawn',
         'Very curious', 1),
        ('Misty', 2, 'Scottish Fold', 'Female', 'Gray',
         'Loves napping', 1),
        ('Shadow', 4, 'Russian Blue', 'Male', 'Silver',
         'Independent', 1),
        ('Tiger', 3, 'Bengal', 'Male', 'Orange',
         'Loves to explore', 2),
        ('Lily', 2, 'Siamese', 'Female', 'Lilac',
         'Quiet and reserved', 2),
        ('Ginger', 4, 'Maine Coon', 'Male', 'Orange',
         'Friendly and social', 2),
        ('Zoe', 1, 'Persian', 'Female', 'White',
         'Playful and curious', 2),
        ('Charlie', 3, 'Abyssinian', 'Male', 'Ruddy',
         'Loves attention', 2),
        ('Sophie', 2, 'Scottish Fold', 'Female', 'Cream',
         'Gentle and affectionate', 2),
        ('Milo', 5, 'Ragdoll', 'Male', 'Blue',
         'Loves cuddles', 2),
        ('Rocky', 3, 'Sphynx', 'Male', 'Gray',
         'Outgoing and friendly', 2),
        ('Lucy', 2, 'Russian Blue', 'Female', 'Silver',
         'Calm and independent', 2),
        ('Maggie', 4, 'British Shorthair', 'Female', 'Blue',
         'Loves being pampered', 2),
        ('Nala', 3, 'Maine Coon', 'Female', 'Brown',
         'Affectionate and playful', 3),
        ('Oscar', 1, 'Siamese', 'Male', 'Seal Point',
         'Energetic and curious', 3),
        ('Whiskers', 4, 'Scottish Fold', 'Female', 'Gray',
         'Loves to snuggle', 3),
        ('Leo', 2, 'Persian', 'Male', 'Black',
         'Quiet and sweet', 3),
        ('Misty', 3, 'British Shorthair', 'Female', 'Gray',
         'Calm and loving', 3),
        ('Chester', 5, 'Bengal', 'Male', 'Spotted',
         'Active and playful', 3),
        ('Milo', 1, 'Sphynx', 'Male', 'Pink',
         'Loves attention', 3),
        ('Sasha', 2, 'Russian Blue', 'Female', 'Blue',
         'Independent and quiet', 3),
        ('Cleo', 3, 'Ragdoll', 'Female', 'Seal',
         'Affectionate and gentle', 3),
        ('Shadow', 4, 'Maine Coon', 'Male', 'Brown',
         'Loves to cuddle', 3),
        ('Simba', 1, 'Bengal', 'Male', 'Spotted',
         'Energetic and playful', 4),
        ('Bella', 3, 'Persian', 'Female', 'White',
         'Calm and affectionate', 4),
        ('Lily', 2, 'Abyssinian', 'Female', 'Ruddy',
         'Friendly and active', 4),
        ('Oscar', 4, 'Scottish Fold', 'Male', 'Cream',
         'Quiet and sweet', 4),
        ('Ginger', 1, 'Siamese', 'Male', 'Blue',
         'Curious and playful', 4),
        ('Cleo', 2, 'Russian Blue', 'Female', 'Silver',
         'Independent and calm', 4),
        ('Max', 5, 'Ragdoll', 'Male', 'Blue',
         'Loves cuddling', 4),
        ('Lucy', 3, 'Maine Coon', 'Female', 'Gray',
         'Gentle and affectionate', 4),
        ('Chester', 4, 'Bengal', 'Male', 'Orange',
         'Active and curious', 4),
        ('Luna', 2, 'British Shorthair', 'Female', 'Blue',
         'Loves attention', 4),
        ('Toby', 3, 'Maine Coon', 'Male', 'Brown',
         'Friendly and active', 5),
        ('Oliver', 2, 'Persian', 'Male', 'White',
         'Loves to relax', 5),
        ('Maggie', 4, 'Bengal', 'Female', 'Spotted',
         'Energetic and playful', 5),
        ('Lucy', 1, 'Sphynx', 'Female', 'Pink',
         'Loves cuddles', 5),
        ('Oscar', 3, 'Abyssinian', 'Male', 'Ruddy',
         'Curious and sweet', 5),
        ('Bella', 2, 'Scottish Fold', 'Female', 'Gray',
         'Loves attention', 5),
        ('Simba', 5, 'British Shorthair', 'Male', 'Blue',
         'Gentle and calm', 5),
        ('Lily', 3, 'Siamese', 'Female', 'Seal',
         'Loves to play', 5),
        ('Rocky', 2, 'Ragdoll', 'Male', 'Blue',
         'Friendly and cuddly', 5),
        ('Misty', 4, 'Russian Blue', 'Female', 'Silver',
         'Independent and sweet', 5),
        ('Toby', 1, 'Bengal', 'Male', 'Orange',
         'Loves to explore', 6),
        ('Luna', 3, 'Maine Coon', 'Female', 'Brown',
         'Affectionate and friendly', 6),
        ('Max', 2, 'Ragdoll', 'Male', 'Blue',
         'Loves cuddles', 6),
        ('Ginger', 3, 'Persian', 'Male', 'Orange',
         'Playful and curious', 6),
        ('Oscar', 4, 'Abyssinian', 'Male', 'Ruddy',
         'Friendly and outgoing', 6),
        ('Maggie', 2, 'Siamese', 'Female', 'Lilac',
         'Calm and gentle', 6),
        ('Bella', 1, 'Scottish Fold', 'Female', 'Cream',
         'Loves to cuddle', 6),
        ('Simba', 4, 'Russian Blue', 'Male', 'Blue',
         'Independent and quiet', 6),
        ('Chester', 2, 'Sphynx', 'Male', 'Gray',
         'Loves attention', 6),
        ('Zoe', 3, 'British Shorthair', 'Female', 'Blue',
         'Loves playing', 6);

-- INSERTING SAMPLE DATA INTO THE CATS ADOPTED TABLE
INSERT INTO CATS_ADOPTED (ADOPTION_DATE, CAT_ID, USER_ID)
VALUES ('2024-01-01', 1, 12),
       ('2024-01-01', 2, 13),
       ('2024-01-10', 4, 14),
       ('2024-01-12', 6, 20),
       ('2024-02-12', 10, 22),
       ('2024-02-12', 11, 22),
       ('2024-02-24', 12, 15),
       ('2024-02-24', 14, 17),
       ('2024-03-28', 16, 35),
       ('2024-04-01', 20, 37),
       ('2024-05-01', 21, 37),
       ('2024-05-03', 22, 37),
       ('2024-05-03', 25, 40),
       ('2024-05-05', 26, 40);

-- INSERTING SAMPLE DATA INTO THE CAT PHOTOS TABLE
INSERT INTO CAT_PHOTOS (CAT_PHOTO_NAME, CAT_ID)
VALUES  ('milo1.jpg', 1),
        ('milo2.jpg', 1),
        ('milo3.jpg', 1),
        ('milo4.jpg', 1),
        ('milo5.jpg', 1),
        ('luna1.jpg', 2),
        ('luna2.jpg', 2),
        ('luna3.jpg', 2),
        ('luna4.jpg', 2),
        ('luna5.jpg', 2),
        ('oliver1.jpg', 3),
        ('oliver2.jpg', 3),
        ('oliver3.jpg', 3),
        ('bella1.jpg', 4),
        ('bella2.jpg', 4),
        ('bella3.jpg', 4),
        ('bella4.jpg', 4),
        ('bella5.jpg', 4),
        ('leo1.jpg', 5),
        ('leo2.jpg', 5),
        ('leo3.jpg', 5),
        ('leo4.jpg', 5),
        ('leo5.jpg', 5),
        ('chloe1.jpg', 6),
        ('chloe2.jpg', 6),
        ('chloe3.jpg', 6),
        ('chloe4.jpg', 6),
        ('max1.jpg', 7),
        ('max2.jpg', 7),
        ('max3.jpg', 7),
        ('max4.jpg', 7),
        ('simba1.jpg', 8),
        ('simba2.jpg', 8),
        ('simba3.jpg', 8),
        ('simba4.jpg', 8),
        ('misty1.jpg', 9),
        ('misty2.jpg', 9),
        ('misty3.jpg', 9),
        ('misty4.jpg', 9),
        ('misty5.jpg', 9),
        ('shadow1.jpg', 10),
        ('shadow2.jpg', 10),
        ('shadow3.jpg', 10),
        ('shadow4.jpg', 10),
        ('shadow5.jpg', 10),
        ('tiger1.jpg', 11),
        ('tiger2.jpg', 11),
        ('tiger3.jpg', 11),
        ('tiger4.jpg', 11),
        ('tiger5.jpg', 11),
        ('lily1.jpg', 12),
        ('lily2.jpg', 12),
        ('lily3.jpg', 12),
        ('ginger1.jpg', 13),
        ('ginger2.jpg', 13),
        ('ginger3.jpg', 13),
        ('ginger4.jpg', 13),
        ('ginger5.jpg', 13),
        ('zoe1.jpg', 14),
        ('zoe2.jpg', 14),
        ('zoe3.jpg', 14),
        ('zoe4.jpg', 14),
        ('charlie1.jpg', 15),
        ('charlie2.jpg', 15),
        ('charlie3.jpg', 15),
        ('charlie4.jpg', 15),
        ('sophie1.jpg', 16),
        ('sophie2.jpg', 16),
        ('sophie3.jpg', 16),
        ('sophie4.jpg', 16),
        ('sophie5.jpg', 16),
        ('rocky1.jpg', 17),
        ('rocky2.jpg', 17),
        ('rocky3.jpg', 17),
        ('lucy1.jpg', 18),
        ('lucy2.jpg', 18),
        ('lucy3.jpg', 18),
        ('lucy4.jpg', 18),
        ('maggie1.jpg', 19),
        ('maggie2.jpg', 19),
        ('maggie3.jpg', 19),
        ('maggie4.jpg', 19),
        ('nala1.jpg', 20),
        ('nala2.jpg', 20),
        ('nala3.jpg', 20),
        ('nala4.jpg', 20),
        ('oscar1.jpg', 21),
        ('oscar2.jpg', 21),
        ('oscar3.jpg', 21),
        ('oscar4.jpg', 21),
        ('whiskers1.jpg', 22),
        ('whiskers2.jpg', 22),
        ('whiskers3.jpg', 22),
        ('whiskers4.jpg', 22),
        ('leo6.jpg', 23),
        ('leo7.jpg', 23),
        ('leo8.jpg', 23),
        ('misty6.jpg', 24),
        ('misty7.jpg', 24),
        ('misty8.jpg', 24),
        ('chester1.jpg', 25),
        ('chester2.jpg', 25),
        ('chester3.jpg', 25),
        ('milo6.jpg', 26),
        ('milo7.jpg', 26),
        ('milo8.jpg', 26),
        ('sasha1.jpg', 27),
        ('sasha2.jpg', 27),
        ('sasha3.jpg', 27),
        ('cleo1.jpg', 28),
        ('cleo2.jpg', 28),
        ('cleo3.jpg', 28),
        ('shadow6.jpg', 29),
        ('shadow7.jpg', 29),
        ('shadow8.jpg', 29),
        ('simba5.jpg', 30),
        ('simba6.jpg', 30),
        ('simba7.jpg', 30),
        ('bella6.jpg', 31),
        ('bella7.jpg', 31),
        ('bella8.jpg', 31),
        ('lily4.jpg', 32),
        ('lily5.jpg', 32),
        ('lily6.jpg', 32),
        ('oscar5.jpg', 33),
        ('oscar6.jpg', 33),
        ('oscar7.jpg', 33),
        ('ginger6.jpg', 34),
        ('ginger7.jpg', 34),
        ('ginger8.jpg', 34),
        ('cleo4.jpg', 35),
        ('cleo5.jpg', 35),
        ('cleo6.jpg', 35),
        ('max5.jpg', 36),
        ('max6.jpg', 36),
        ('max7.jpg', 36),
        ('lucy5.jpg', 37),
        ('lucy6.jpg', 37),
        ('lucy7.jpg', 37),
        ('chester4.jpg', 38),
        ('chester5.jpg', 38),
        ('chester6.jpg', 38),
        ('luna6.jpg', 39),
        ('luna7.jpg', 39),
        ('luna8.jpg', 39),
        ('luna9.jpg', 39),
        ('toby1.jpg', 40),
        ('toby2.jpg', 40),
        ('toby3.jpg', 40),
        ('oliver4.jpg', 41),
        ('oliver5.jpg', 41),
        ('oliver6.jpg', 41),
        ('maggie5.jpg', 42),
        ('maggie6.jpg', 42),
        ('maggie7.jpg', 42),
        ('lucy8.jpg', 43),
        ('lucy9.jpg', 43),
        ('lucy10.jpg', 43),
        ('oscar8.jpg', 44),
        ('oscar9.jpg', 44),
        ('oscar10.jpg', 44),
        ('bella9.jpg', 45),
        ('bella10.jpg', 45),
        ('bella11.jpg', 45),
        ('simba8.jpg', 46),
        ('simba9.jpg', 46),
        ('simba10.jpg', 46),
        ('lilly7.jpg', 47),
        ('lilly8.jpg', 47),
        ('lilly9.jpg', 47),
        ('rocky4.jpg', 48),
        ('rocky5.jpg', 48),
        ('rocky6.jpg', 48),
        ('misty9.jpg', 49),
        ('misty10.jpg', 49),
        ('misty11.jpg', 49),
        ('toby4.jpg', 50),
        ('toby5.jpg', 50),
        ('toby6.jpg', 50),
        ('whiskers5.jpg', 51),
        ('whiskers6.jpg', 51),
        ('whiskers7.jpg', 51),
        ('charlie5.jpg', 52),
        ('charlie6.jpg', 52),
        ('charlie7.jpg', 52),
        ('leo9.jpg', 53),
        ('leo10.jpg', 53),
        ('leo11.jpg', 53),
        ('ginger9.jpg', 54),
        ('ginger10.jpg', 54),
        ('ginger11.jpg', 54),
        ('sophie6.jpg', 55),
        ('sophie7.jpg', 55),
        ('sophie8.jpg', 55),
        ('tiger6.jpg', 56),
        ('tiger7.jpg', 56),
        ('tiger8.jpg', 56),
        ('shadow9.jpg', 57),
        ('shadow10.jpg', 57),
        ('shadow11.jpg', 57),
        ('sasha4.jpg', 58),
        ('sasha5.jpg', 58),
        ('sasha6.jpg', 58),
        ('milo8.jpg', 59),
        ('milo9.jpg', 59),
        ('milo10.jpg', 59),
        ('chloe5.jpg', 60),
        ('chloe6.jpg', 60),
        ('chloe7.jpg', 60);

-- INSERTING SAMPLE DATA INTO THE GROUP TABLE
INSERT INTO "GROUP" (NAME)
VALUES  ('Staff'),
        ('Shelter_staff'),
        ('User');

-- INSERTING SAMPLE DATA INTO THE PERMISSION TABLE
INSERT INTO PERMISSION (NAME, CODE_NAME)
VALUES
        -- Permissions related to users
        ('Add user', 'add_user'),
        ('View user', 'view_user'),
        ('Change user information', 'change_user'),
        ('Delete user', 'delete_user'),

        -- Permissions related to shelter staff
        ('Add shelter staff', 'add_shelter_staff'),
        ('View shelter staff', 'view_shelter_staff'),
        ('Change shelter staff information', 'change_shelter_staff'),
        ('Delete shelter staff', 'delete_shelter_staff'),

        -- Permissions related to shelters
        ('Add shelter', 'add_shelter'),
        ('View shelter', 'view_shelter'),
        ('Change shelter information', 'change_shelter'),
        ('Delete shelter', 'delete_shelter'),

        -- Permissions related to cats for adoption
        ('Add cat for adoption', 'add_cat_for_adoption'),
        ('View cats for adoption', 'view_cats_for_adoption'),
        ('Change cat for adoption information', 'change_cat_for_adoption'),
        ('Delete cat for adoption', 'delete_cat_for_adoption'),

        -- Permissions related to cat photos
        ('Add cat photo', 'add_cat_photo'),
        ('View cat photos', 'view_cat_photos'),
        ('Change cat photo information', 'change_cat_photo'),
        ('Delete cat photo', 'delete_cat_photo'),

        -- Permissions related to adopted cats
        ('Add adopted cat', 'add_cat_adopted'),
        ('View adopted cat', 'view_cat_adopted'),
        ('Change adopted cat information', 'change_cat_adopted'),
        ('Delete adopted cat', 'delete_cat_adopted');

-- INSERTING SAMPLE DATA INTO THE GROUP PERMISSIONS TABLE
INSERT INTO GROUP_PERMISSIONS (GROUP_ID, PERMISSION_ID)
VALUES
        -- Staff Permissions
        (1, 1),
        (1, 2),
        (1, 3),
        (1, 4),
        (1, 5),
        (1, 6),
        (1, 7),
        (1, 8),
        (1, 9),
        (1, 10),
        (1, 11),
        (1, 12),
        (1, 13),
        (1, 14),
        (1, 15),
        (1, 16),
        (1, 17),
        (1, 18),
        (1, 19),
        (1, 20),
        (1, 21),
        (1, 22),
        (1, 23),
        (1, 24),

        -- Shelter Staff Permissions
        (2, 13),
        (2, 14),
        (2, 15),
        (2, 16),
        (2, 17),
        (2, 18),
        (2, 19),
        (2, 20),
        (2, 21),
        (2, 22),
        (2, 23),
        (2, 24),

        -- Users Permissions
        (3, 10),
        (3, 14),
        (3, 18),
        (3, 21);

-- INSERTING SAMPLE DATA INTO THE USER GROUPS TABLE
INSERT INTO USER_GROUPS (USER_ID, GROUP_ID)
VALUES
        -- Staff related to group staff
        (2, 1),
        (3, 1),
        (4, 1),

        -- Staff shelter related to group staff shelter
        (5, 1),
        (6, 1),
        (7, 1),

        -- user related to group user
        (8, 3),
        (9, 3),
        (10, 3),
        (11, 3),
        (12, 3),
        (13, 3),
        (14, 3),
        (15, 3),
        (16, 3),
        (17, 3),
        (18, 3),
        (19, 3),
        (20, 3),
        (21, 3),
        (22, 3),
        (23, 3),
        (24, 3),
        (25, 3),
        (26, 3),
        (27, 3),
        (28, 3),
        (29, 3),
        (30, 3),
        (31, 3),
        (32, 3),
        (33, 3),
        (34, 3),
        (35, 3),
        (36, 3),
        (37, 3),
        (38, 3),
        (39, 3),
        (40, 3),
        (41, 3),
        (42, 3),
        (43, 3);
